create table cliente (id integer generated by default as identity, data_nascimento date not null, nome varchar(255),
                      numero_conta varchar(6), plano_exclusive boolean not null, saldo numeric(38,2), primary key (id));
create table historico_transacao (id integer generated by default as identity, numero_conta varchar(255),
                                  valor numeric(38,2), data_movimentacao date, plano_exclusive boolean not null,
                                  tipo_transacao tinyint check (tipo_transacao between 0 and 1), primary key (id));
create table taxa (id integer generated by default as identity, porcentagem float(24) not null,
                   valor_inicial numeric(38,2), primary key (id));
alter table if exists cliente add constraint UK_fc1mhsribfhwwqj1b4g0ci52v unique (numero_conta);

insert into cliente (data_nascimento,nome,numero_conta,plano_exclusive,saldo,id) values
    ('1999-12-01','wesley lima','181111',true,15000,default),
    ('2009-07-06','xavier antonov','172145',false,3000,default);

insert into taxa (valor_inicial, porcentagem, id) values
    (300, 0.01, default),
    (100, 0.004, default);